/*
    requirejs配置
 */
require.config({
    paths:{
        jquery:'../lib/jquery-3.2.1',
        common:'../js/common',
        jqzoom:'../lib/jquery.gdsZoom/jquery.gdsZoom'
    },
    shim:{
        common:['jquery'],
        jqzoom:['jquery']
    }
});